/**
 * Seed «Куда сходить в Сочи» — реальные места Сочи 2026.
 * Usage: node scripts/seed-places.mjs
 * Requires DATABASE_URL and prisma generate.
 */
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const connectionString =
  process.env.DATABASE_URL ||
  'postgresql://sochi:sochi@127.0.0.1:5432/sochi_portal?schema=public';
const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString }),
});

function features(items) {
  return JSON.stringify(items);
}

function packTips(howToGet, tips) {
  const bits = [];
  if (howToGet) bits.push(`Как добраться: ${howToGet}`);
  if (tips) bits.push(tips);
  return bits.join(' ') || null;
}

const PLACES = [
  {
    id: 'place_olympic_park',
    slug: 'olimpiyskiy-park',
    title: 'Олимпийский парк',
    summary: 'Медаль-плаза, фонтаны и арены Игр-2014 у Чёрного моря.',
    description:
      'Сердце Имеретинской низменности: Олимпийский парк с Медаль-плазой, поющим фонтаном, ледовыми дворцами и променадом к морю. Вечером особенно красиво — огни арен и шоу фонтанов. Удобно совмещать с Имеретинским пляжем и Сочи-Парком.',
    category: 'UNIQUE',
    address: 'г. Сочи, Адлер, Олимпийский парк',
    district: 'Адлер / Имеретинская',
    lat: 43.4055,
    lng: 39.9555,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
    bestSeason: 'Круглый год, вечерние шоу — май–октябрь',
    visitTime: '2–4 часа',
    priceHint: 'Парк бесплатно; музеи и арены — примерно от 300 ₽',
    sortOrder: 10,
    featuresJson: features([
      { icon: 'sparkles', title: 'Шоу фонтанов', text: 'Вечерняя подсветка и музыка на Медаль-плазе' },
      { icon: 'bike', title: 'Велопрокат', text: 'Круговой маршрут вокруг арен' },
      { icon: 'camera', title: 'Фото-точки', text: 'Олимпийский огонь, кольца, панорама моря' },
    ]),
    tips: 'Приезжайте к закату: меньше жары и лучше свет. Парковка у арен платная в пик сезона.',
    howToGet: 'Ласточка до «Олимпийский парк» или автобусы 125, 105к от Адлера; пешком от Имеретинского пляжа.',
  },
  {
    id: 'place_rosa_khutor',
    slug: 'roza-khutor',
    title: 'Роза Хутор / Красная Поляна',
    summary: 'Горы, канатки и променад курортного посёлка.',
    description:
      'Курортный кластер Красной Поляны: Роза Хутор с набережной Мзымты, канатными дорогами и видами на хребты. Летом — трекинг и смотровые, зимой — лыжи и сноуборд. Рядом Газпром и Красная Поляна Resort.',
    category: 'MOUNTAIN',
    address: 'г. Сочи, Эсто-Садок, Роза Хутор',
    district: 'Красная Поляна',
    lat: 43.6725,
    lng: 40.2975,
    image: 'https://images.unsplash.com/photo-1551524164-687a55dd1126?w=1200&q=80',
    bestSeason: 'Зима — снег; лето — треккинг и виды',
    visitTime: 'Полный день',
    priceHint: 'Канатки примерно от 1 500 ₽ за подъём, сезон меняет тариф',
    sortOrder: 20,
    featuresJson: features([
      { icon: 'mountain', title: 'Канатки', text: 'Подъём на плато с панорамой Кавказа' },
      { icon: 'footprints', title: 'Тропы', text: 'Летние маршруты разной сложности' },
      { icon: 'coffee', title: 'Променад', text: 'Кафе и магазины у реки Мзымта' },
    ]),
    tips: 'Билеты на канатку лучше брать онлайн. На высоте прохладнее — возьмите ветровку.',
    howToGet: 'Ласточка до «Роза Хутор» или «Эсто-Садок»; далее пешком по набережной Мзымты.',
  },
  {
    id: 'place_dendrarium',
    slug: 'dendrarium',
    title: 'Дендрарий',
    summary: 'Ботанический сад с субтропиками и видовой башней.',
    description:
      'Сочинский дендрарий — классика города: аллеи, редкие деревья, пруд с лебедями и канатная дорога к верхней площадке. Отсюда открывается вид на море и курортный проспект.',
    category: 'PARK',
    address: 'г. Сочи, Курортный пр., 74',
    district: 'Центр / Хостинский',
    lat: 43.5697,
    lng: 39.7415,
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
    bestSeason: 'Весна–осень; зимой тоже зелено',
    visitTime: '1,5–3 часа',
    priceHint: 'Вход примерно 320–400 ₽, канатка отдельно ~350 ₽',
    sortOrder: 30,
    featuresJson: features([
      { icon: 'leaf', title: 'Коллекция растений', text: 'Субтропики со всего мира' },
      { icon: 'cable', title: 'Канатка', text: 'Подъём к видовой площадке' },
      { icon: 'bird', title: 'Пруд', text: 'Лебеди и фото у воды' },
    ]),
    tips: 'Удобная обувь — много подъёмов. Утром меньше людей и мягче свет.',
  },
  {
    id: 'place_agura',
    slug: 'agurskie-vodopady',
    title: 'Агурские водопады',
    summary: 'Лесная тропа к каскадам у Орлиных скал.',
    description:
      'Один из самых популярных природных маршрутов Сочи: тропа вдоль Агуры к нижнему, среднему и верхнему водопадам. Можно продолжить путь к Орлиным скалам и смотровым площадкам.',
    category: 'MOUNTAIN',
    address: 'г. Сочи, ущелье реки Агура',
    district: 'Хоста',
    lat: 43.55,
    lng: 39.825,
    image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=1200&q=80',
    bestSeason: 'Апрель–октябрь; после дождей водопады полноводнее',
    visitTime: '2–4 часа',
    priceHint: 'Вход на тропу примерно 200–300 ₽',
    sortOrder: 40,
    featuresJson: features([
      { icon: 'droplets', title: 'Каскады', text: 'Три основных водопада на маршруте' },
      { icon: 'trees', title: 'Тень леса', text: 'Спасение в жаркий день' },
      { icon: 'boot', title: 'Треккинг', text: 'Средняя сложность, есть ступени' },
    ]),
    tips: 'Нескользящая обувь обязательна. Возьмите воду — на тропе мало точек продажи.',
  },
  {
    id: 'place_akhun',
    slug: 'orlinye-skaly-akhun',
    title: 'Орлиные скалы / гора Ахун',
    summary: 'Смотровые над Хостой и башня на Ахуне.',
    description:
      'Орлиные скалы — каменные уступы с видами на море и ущелье Агуры. Рядом маршрут к горе Ахун со смотровой башней: панорама от центра Сочи до Адлера в ясную погоду.',
    category: 'VIEWPOINT',
    address: 'г. Сочи, Орлиные скалы / гора Ахун',
    district: 'Хоста',
    lat: 43.5508,
    lng: 39.843,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
    bestSeason: 'Ясные дни весна–осень',
    visitTime: '2–3 часа',
    priceHint: 'Башня Ахун примерно 150–250 ₽; Орлиные скалы — по тарифу тропы',
    sortOrder: 50,
    featuresJson: features([
      { icon: 'eye', title: 'Панорама', text: 'Море, горы и курортная линия' },
      { icon: 'mountain', title: 'Башня Ахун', text: 'Классическая смотровая Сочи' },
      { icon: 'camera', title: 'Рассвет/закат', text: 'Лучшее время для кадров' },
    ]),
    tips: 'Совместите с Агурскими водопадами за один день. На смотровых ветрено.',
  },
  {
    id: 'place_tis_samshit',
    slug: 'tiso-samshitovaya-roshcha',
    title: 'Тисо-самшитовая роща',
    summary: 'Древний лес Кавказского заповедника у Хосты.',
    description:
      'Участок Кавказского биосферного заповедника: тис и самшит, карстовые скалы и тенистые тропы. Короткий и большой круги — на выбор. Важный природный объект Большого Сочи.',
    category: 'PARK',
    address: 'г. Сочи, Хоста, Тисо-самшитовая роща',
    district: 'Хоста',
    lat: 43.543,
    lng: 39.842,
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&q=80',
    bestSeason: 'Круглый год; летом прохладно в тени',
    visitTime: '1–2,5 часа',
    priceHint: 'Вход заповедника примерно 300–400 ₽',
    sortOrder: 60,
    featuresJson: features([
      { icon: 'shield', title: 'Заповедник', text: 'Охраняемый реликтовый лес' },
      { icon: 'route', title: 'Два круга', text: 'Короткий и большой маршруты' },
      { icon: 'leaf', title: 'Реликты', text: 'Тис и самшит тысячелетней истории' },
    ]),
    tips: 'Не сходите с троп — это заповедник. Комары бывают в тёплый сезон.',
  },
  {
    id: 'place_sochi_park',
    slug: 'sochi-park',
    title: 'Сочи-Парк',
    summary: 'Темапарк у Олимпийского парка для всей семьи.',
    description:
      'Крупный парк аттракционов рядом с Олимпийским парком: американские горки, зоны для малышей, шоу и вечерняя атмосфера. Удобно после прогулки по Медаль-плазе.',
    category: 'FAMILY',
    address: 'г. Сочи, Адлер, ул. Международная, 6',
    district: 'Адлер / Имеретинская',
    lat: 43.405,
    lng: 39.965,
    image: 'https://images.unsplash.com/photo-1513889961551-628c1e5e2ee9?w=1200&q=80',
    bestSeason: 'Сезон аттракционов: весна–осень',
    visitTime: 'Полный день',
    priceHint: 'День в парке примерно от 2 000 ₽, детям обычно дешевле',
    sortOrder: 70,
    featuresJson: features([
      { icon: 'ferris', title: 'Аттракционы', text: 'Горки и зоны для разного возраста' },
      { icon: 'users', title: 'Семья', text: 'Детские площадки и шоу' },
      { icon: 'ticket', title: 'День-пакет', text: 'Удобно брать билет на весь день' },
    ]),
    tips: 'В выходные очереди длиннее — приходите к открытию. Солнцезащитный крем обязателен.',
  },
  {
    id: 'place_riviera',
    slug: 'plyazh-riviera',
    title: 'Центральный / Ривьера пляж',
    summary: 'Городской пляж у парка «Ривьера» в центре.',
    description:
      'Популярный городской пляж и парк «Ривьера»: галька, шезлонги, кафе и набережная. Удобная точка, если живёте в центре и не хотите ехать в Адлер.',
    category: 'BEACH',
    address: 'г. Сочи, парк Ривьера / пляж Ривьера',
    district: 'Центр',
    lat: 43.5885,
    lng: 39.7165,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
    bestSeason: 'Июнь–сентябрь',
    visitTime: '2–5 часов',
    priceHint: 'Пляж бесплатный; лежаки примерно от 300 ₽',
    sortOrder: 80,
    featuresJson: features([
      { icon: 'waves', title: 'Море в городе', text: 'Быстрый доступ из центра' },
      { icon: 'trees', title: 'Парк рядом', text: 'Ривьера — прогулки и тень' },
      { icon: 'utensils', title: 'Кафе', text: 'Много точек на набережной' },
    ]),
    tips: 'Утром меньше людей. Возьмите аквашузы — галька.',
  },
  {
    id: 'place_imeretinka',
    slug: 'imeretinskiy-plyazh',
    title: 'Имеретинский пляж',
    summary: 'Широкая береговая линия у Олимпийского парка.',
    description:
      'Пляжная зона Имеретинской низменности: длинный берег, современная инфраструктура и близость к Олимпийскому парку. Хороший выбор для спокойного дня у моря после осмотра арен.',
    category: 'BEACH',
    address: 'г. Сочи, Адлер, Имеретинская низменность',
    district: 'Адлер / Имеретинская',
    lat: 43.4,
    lng: 39.97,
    image: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=1200&q=80',
    bestSeason: 'Июнь–сентябрь',
    visitTime: 'Полдня',
    priceHint: 'Муниципальный участок бесплатно; лежаки — по прайсу зоны',
    sortOrder: 90,
    featuresJson: features([
      { icon: 'sun', title: 'Широкий берег', text: 'Места хватает даже в сезон' },
      { icon: 'map', title: 'Рядом Олимппарк', text: 'Можно совместить за день' },
      { icon: 'wind', title: 'Променад', text: 'Прогулки вдоль моря' },
    ]),
    tips: 'Ветер с моря бывает сильнее, чем в центре. Проверьте флаги и спасателей.',
  },
  {
    id: 'place_skypark',
    slug: 'skypark',
    title: 'Скайпарк',
    summary: 'Подвесной мост и адреналин над ущельем Ахцу.',
    description:
      'Sochi Skypark AJ Hackett: подвесной мост, банджи, зиплайн и виды на ущелье. Один из самых «вау»-объектов курорта — даже если просто пройтись по мосту без прыжков.',
    category: 'UNIQUE',
    address: 'г. Сочи, Скайпарк, ущелье Ахцу',
    district: 'Красная Поляна / Ахцу',
    lat: 43.525,
    lng: 39.88,
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&q=80',
    bestSeason: 'Круглый год при хорошей погоде',
    visitTime: '2–4 часа',
    priceHint: 'Проход по мосту примерно от 1 500 ₽; прыжки дороже',
    sortOrder: 100,
    featuresJson: features([
      { icon: 'bridge', title: 'Мост', text: 'Подвесная конструкция над ущельем' },
      { icon: 'zap', title: 'Адреналин', text: 'Банджи и зиплайн для смелых' },
      { icon: 'camera', title: 'Виды', text: 'Фото с высоты без прыжка' },
    ]),
    tips: 'При сильном ветре аттракции могут закрыть. Бронируйте слоты заранее в сезон.',
  },
  {
    id: 'place_vorontsov',
    slug: 'vorontsovskie-peshchery',
    title: 'Воронцовские пещеры',
    summary: 'Карстовые залы в горах над Хостой.',
    description:
      'Система Воронцовских пещер — экскурсионный маршрут по подземным галереям с натёчными формами. Температура внутри прохладная круглый год. Отличный контраст к пляжному Сочи.',
    category: 'UNIQUE',
    address: 'г. Сочи, Воронцовские пещеры',
    district: 'Хоста / горы',
    lat: 43.615,
    lng: 39.94,
    image: 'https://images.unsplash.com/photo-1504214208698-94b0d02d8e1c?w=1200&q=80',
    bestSeason: 'Круглый год',
    visitTime: '1,5–2,5 часа',
    priceHint: 'Экскурсия примерно 400–600 ₽',
    sortOrder: 110,
    featuresJson: features([
      { icon: 'cave', title: 'Подземелье', text: 'Карстовые залы и коридоры' },
      { icon: 'thermometer', title: 'Прохлада', text: 'Спасение в жару' },
      { icon: 'guide', title: 'Экскурсия', text: 'Лучше с гидом по маршруту' },
    ]),
    tips: 'Куртка или кофта — внутри ~12°C. Удобная обувь без каблуков.',
  },
  {
    id: 'place_matsesta',
    slug: 'matsesta',
    title: 'Мацеста',
    summary: 'Легендарные сероводородные источники Сочи.',
    description:
      'Мацеста — символ курортного Сочи: бальнеология, характерный запах источников и история советского здравкурорта. Можно совместить с прогулкой по долине и осмотром окрестностей.',
    category: 'HISTORICAL',
    address: 'г. Сочи, Мацеста',
    district: 'Хостинский',
    lat: 43.545,
    lng: 39.795,
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&q=80',
    bestSeason: 'Круглый год',
    visitTime: '1–3 часа',
    priceHint: 'Прогулка бесплатно; процедуры — прайс санатория',
    sortOrder: 120,
    featuresJson: features([
      { icon: 'droplet', title: 'Источники', text: 'Сероводородные воды курорта' },
      { icon: 'landmark', title: 'История', text: 'Классика сочинской здравницы' },
      { icon: 'heart', title: 'Релакс', text: 'Спокойный день без гонок' },
    ]),
    tips: 'Процедуры — по записи и показаниям. Для прогулки хватит долины и видов.',
  },
  {
    id: 'place_marine_station',
    slug: 'morskoy-vokzal',
    title: 'Морской вокзал',
    summary: 'Визитная открытка центральной набережной.',
    description:
      'Морской вокзал Сочи — архитектурная доминанта набережной: башня со шпилем, скульптуры времён года и прогулочная зона у причалов. Отсюда начинаются морские прогулки и фотосессии.',
    category: 'HISTORICAL',
    address: 'г. Сочи, ул. Войкова, 1',
    district: 'Центр',
    lat: 43.5805,
    lng: 39.7185,
    image: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1200&q=80',
    bestSeason: 'Круглый год; особенно красиво вечером',
    visitTime: '45–90 минут',
    priceHint: 'Набережная бесплатно; катер примерно от 500 ₽',
    sortOrder: 130,
    featuresJson: features([
      { icon: 'landmark', title: 'Архитектура', text: 'Шпиль и скульптуры у причала' },
      { icon: 'ship', title: 'Море', text: 'Прогулочные катера' },
      { icon: 'camera', title: 'Открытка', text: 'Одна из главных фототочек города' },
    ]),
    tips: 'Закат и вечерняя подсветка — лучшее время. Рядом набережная и центр.',
  },
  {
    id: 'place_history_museum',
    slug: 'muzey-istorii-sochi',
    title: 'Музей истории Сочи',
    summary: 'Город от черкесских аулов до Олимпиады.',
    description:
      'Музей истории города-курорта: экспозиции о природе, этнографии, курортном строительстве и Олимпиаде-2014. Хорошая точка, если хотите понять Сочи глубже пляжей и канаток.',
    category: 'MUSEUM',
    address: 'г. Сочи, ул. Воронова, 2',
    district: 'Центр',
    lat: 43.585,
    lng: 39.725,
    image: 'https://images.unsplash.com/photo-1566127444979-b3d2b64d626b?w=1200&q=80',
    bestSeason: 'Круглый год; удобно в дождь',
    visitTime: '1–2 часа',
    priceHint: 'Вход примерно 150–250 ₽',
    sortOrder: 140,
    featuresJson: features([
      { icon: 'book', title: 'Экспозиции', text: 'От древности до Игр-2014' },
      { icon: 'cloud-rain', title: 'План Б', text: 'Идеально в непогоду' },
      { icon: 'brain', title: 'Контекст', text: 'Понять город за час-два' },
    ]),
    tips: 'Проверьте часы работы перед визитом. Можно совместить с прогулкой по центру.',
  },
  {
    id: 'place_33_falls',
    slug: '33-vodopada',
    title: '33 водопада',
    summary: 'Каскады в ущелье реки Шахе — классика Лазаревского.',
    description:
      'Природно-этнографический комплекс «33 водопада» в долине Джегош: лесные тропы, купальни у нижних каскадов и колорит Лазаревского района. Один из самых узнаваемых «природных» маршрутов Большого Сочи.',
    category: 'MOUNTAIN',
    address: 'г. Сочи, Лазаревский р-н, аул Большой Кичмай / 33 водопада',
    district: 'Лазаревское',
    lat: 43.825,
    lng: 39.575,
    image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=1200&q=80',
    bestSeason: 'Май–октябрь; после дождей полноводнее',
    visitTime: '3–5 часов с дорогой',
    priceHint: 'Вход в комплекс примерно 400–600 ₽',
    sortOrder: 150,
    featuresJson: features([
      { icon: 'droplets', title: 'Каскады', text: 'Серия водопадов в ущелье' },
      { icon: 'trees', title: 'Лес', text: 'Тень и прохлада в жару' },
      { icon: 'car', title: 'День-трип', text: 'Удобно как выезд из центра' },
    ]),
    tips: 'Дорога занимает время — планируйте полный день. Обувь с протектором обязательна.',
  },
  {
    id: 'place_stalin_dacha',
    slug: 'dacha-stalina',
    title: 'Дача Сталина',
    summary: 'Историческая резиденция в зелени над Мацестой.',
    description:
      'Зелёная дача на крутом склоне — музейный объект с атмосферой середины XX века, видами на море и экскурсионными маршрутами. Важная историческая точка для тех, кто собирает «старый Сочи».',
    category: 'HISTORICAL',
    address: 'г. Сочи, Курортный пр. / Зелёная роща (Мацеста)',
    district: 'Хостинский',
    lat: 43.55,
    lng: 39.78,
    image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&q=80',
    bestSeason: 'Круглый год',
    visitTime: '1–2 часа',
    priceHint: 'Экскурсия примерно 300–500 ₽',
    sortOrder: 160,
    featuresJson: features([
      { icon: 'landmark', title: 'История', text: 'Резиденция эпохи курортного Сочи' },
      { icon: 'tree', title: 'Роща', text: 'Теневой склон над морем' },
      { icon: 'guide', title: 'Экскурсия', text: 'Лучше с гидом по интерьерам' },
    ]),
    tips: 'Билеты лучше брать заранее в сезон. Совмещается с Мацестой.',
  },
  {
    id: 'place_navaginskaya',
    slug: 'navaginskaya',
    title: 'Навагинская улица',
    summary: 'Пешеходная артерия центра с кафе и фонтанами.',
    description:
      'Главная прогулочная улица центра Сочи: фонтаны, уличные музыканты, магазины и выход к Морскому вокзалу. База для вечернего маршрута «центр → набережная → вокзал».',
    category: 'UNIQUE',
    address: 'г. Сочи, ул. Навагинская',
    district: 'Центр',
    lat: 43.5858,
    lng: 39.7195,
    image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=1200&q=80',
    bestSeason: 'Круглый год; особенно вечер летом',
    visitTime: '1–2 часа',
    priceHint: 'Бесплатно',
    sortOrder: 170,
    featuresJson: features([
      { icon: 'footprints', title: 'Променад', text: 'Пешеходная зона без машин' },
      { icon: 'coffee', title: 'Кафе', text: 'Точки на любой вкус' },
      { icon: 'moon', title: 'Вечер', text: 'Подсветка и живая атмосфера' },
    ]),
    tips: 'В пик сезона людно после 19:00. Удобная точка старта вечернего маршрута.',
  },
  {
    id: 'place_winter_theater',
    slug: 'zimniy-teatr',
    title: 'Зимний театр',
    summary: 'Колоннада и сцена курортного Сочи на Курортном проспекте.',
    description:
      'Зимний театр — архитектурная доминанта Курортного проспекта с колоннадой и регулярной афишей. Рядом парк и выход к морю: удобно для культурного вечера или дневной прогулки по «парадному» Сочи.',
    category: 'HISTORICAL',
    address: 'г. Сочи, Театральная пл., 2',
    district: 'Центр',
    lat: 43.5755,
    lng: 39.7255,
    image: 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80',
    bestSeason: 'Круглый год по афише',
    visitTime: 'Спектакль или 30–60 мин снаружи',
    priceHint: 'Снаружи бесплатно; билеты — по афише театра',
    sortOrder: 180,
    featuresJson: features([
      { icon: 'landmark', title: 'Архитектура', text: 'Колоннада и площадь' },
      { icon: 'ticket', title: 'Афиша', text: 'Концерты и спектакли' },
      { icon: 'camera', title: 'Фото', text: 'Классический кадр курорта' },
    ]),
    tips: 'Проверьте афишу заранее. Днём красиво для фото, вечером — атмосфера премьеры.',
  },
  {
    id: 'place_yuzhnye_kultury',
    slug: 'yuzhnye-kultury',
    title: 'Парк «Южные культуры»',
    summary: 'Исторический дендропарк у Имеретинской низменности.',
    description:
      'Парк «Южные культуры» в Адлере — тенистые аллеи, пруды и коллекция субтропических растений рядом с Олимпийским парком. Спокойнее дендрария в пик сезона и удобен, если уже гуляете по Имеретинке.',
    category: 'PARK',
    address: 'г. Сочи, Адлер, ул. Нагорный тупик / Южные культуры',
    district: 'Адлер',
    lat: 43.417,
    lng: 39.973,
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&q=80',
    bestSeason: 'Весна–осень',
    visitTime: '1,5–3 часа',
    priceHint: 'Вход примерно 250–350 ₽',
    sortOrder: 190,
    featuresJson: features([
      { icon: 'leaf', title: 'Пруды и аллеи', text: 'Тише, чем на набережной' },
      { icon: 'camera', title: 'Фото', text: 'Мостики и редкие деревья' },
      { icon: 'map', title: 'Рядом Имеретинка', text: 'Совмещается с пляжем и Олимппарком' },
    ]),
    tips: 'Удобная обувь: дорожки после дождя скользкие.',
    howToGet: 'Автобусы к Олимпийскому парку, далее 10–15 минут пешком или такси от Адлера.',
  },
  {
    id: 'place_oceanarium',
    slug: 'okeanarium-adler',
    title: 'Сочинский океанариум',
    summary: 'Акулы, тоннель и экспозиция у Адлера — план на дождь.',
    description:
      'Sochi Discovery World Aquarium — крупный океанариум с подводным тоннелем. Хороший семейный маршрут, когда море штормит или хочется дня без жары. Рядом торговые и пляжные зоны Адлера.',
    category: 'FAMILY',
    address: 'г. Сочи, Адлер, ул. Ленина / океанариум',
    district: 'Адлер',
    lat: 43.438,
    lng: 39.91,
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=80',
    bestSeason: 'Круглый год; особенно в дождь',
    visitTime: '1,5–2,5 часа',
    priceHint: 'Вход примерно от 1 000 ₽, детям дешевле',
    sortOrder: 200,
    featuresJson: features([
      { icon: 'droplet', title: 'Тоннель', text: 'Акулы и скаты над головой' },
      { icon: 'users', title: 'Семья', text: 'Понятный маршрут с детьми' },
      { icon: 'cloud-rain', title: 'План Б', text: 'Не зависит от моря' },
    ]),
    tips: 'Билеты онлайн в выходные экономят очередь. В зале прохладно — кофта не помешает.',
    howToGet: 'Ласточка или электричка до Адлера, далее автобус/такси по Ленина.',
  },
  {
    id: 'place_laura_aviary',
    slug: 'volernyy-kompleks-laura',
    title: 'Вольерный комплекс Лаура',
    summary: 'Кавказский заповедник: увидеть зверей без дальнего трека.',
    description:
      'Вольерный комплекс Кавказского заповедника на Лауре: олени, туры, хищные птицы и рассказ о природе Западного Кавказа. Удобно совмещать с Красной Поляной, если не готовы к длинному походу.',
    category: 'FAMILY',
    address: 'г. Сочи, Красная Поляна, пос. Эти, Лаура',
    district: 'Красная Поляна',
    lat: 43.69,
    lng: 40.2,
    image: 'https://images.unsplash.com/photo-1456926631375-92c8ce872def?w=1200&q=80',
    bestSeason: 'Круглый год, лучше в сухую погоду',
    visitTime: '1–2 часа',
    priceHint: 'Вход примерно 400–600 ₽',
    sortOrder: 210,
    featuresJson: features([
      { icon: 'bird', title: 'Животные Кавказа', text: 'Вольеры заповедника' },
      { icon: 'leaf', title: 'Просветительский маршрут', text: 'Коротко и по делу' },
      { icon: 'mountain', title: 'Рядом курорты', text: 'Газпром / Поляна 960' },
    ]),
    tips: 'Не кормите животных. После дождя дорожки грязные.',
    howToGet: 'Ласточка до «Эсто-Садок» или «Красная Поляна», далее автобус/такси на Лауру.',
  },
  {
    id: 'place_orekhovka',
    slug: 'orekhovskiy-vodopad',
    title: 'Ореховский водопад',
    summary: 'Ближний каскад к центру — на полдня без дальнего выезда.',
    description:
      'Ореховский водопад на реке Безуменке ближе к центру, чем 33 водопада. Тропа короче, но после дождя скользкая. Хороший «первый» водопад, если не хотите ехать в Лазаревское.',
    category: 'MOUNTAIN',
    address: 'г. Сочи, село Ореховка',
    district: 'Хостинский / Ореховка',
    lat: 43.59,
    lng: 39.8,
    image: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=1200&q=80',
    bestSeason: 'Апрель–октябрь; полноводнее после дождей',
    visitTime: '1,5–3 часа',
    priceHint: 'Вход на тропу примерно 150–250 ₽',
    sortOrder: 220,
    featuresJson: features([
      { icon: 'droplets', title: 'Каскад', text: 'Близко к городу' },
      { icon: 'boot', title: 'Короткая тропа', text: 'Подъём, не прогулка в кедах' },
      { icon: 'trees', title: 'Тень', text: 'Спасение в жару' },
    ]),
    tips: 'Нескользящая обувь. Не купайтесь у кромки — скользко.',
    howToGet: 'Автобус в сторону Ореховки от центра / Мацесты; часть пути пешком в гору.',
  },
  {
    id: 'place_zmeykovskie',
    slug: 'zmeykovskie-vodopady',
    title: 'Змейковские водопады',
    summary: 'Цепочка каскадов в зелёном ущелье над Мацестой.',
    description:
      'Змейковские водопады — несколько ступеней на ручье в Хостинском районе. Маршрут короче Агуры, но тоже требует нормальной обуви. Удобно после Мацесты, если остаётся светлое время.',
    category: 'MOUNTAIN',
    address: 'г. Сочи, Змейковские водопады',
    district: 'Хостинский',
    lat: 43.56,
    lng: 39.82,
    image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=1200&q=80',
    bestSeason: 'Май–октябрь',
    visitTime: '2–3 часа',
    priceHint: 'Вход примерно 200–300 ₽',
    sortOrder: 230,
    featuresJson: features([
      { icon: 'droplets', title: 'Несколько каскадов', text: 'Можно выбрать длину прогулки' },
      { icon: 'trees', title: 'Лес', text: 'Тень и влажный воздух' },
      { icon: 'camera', title: 'Кадры у воды', text: 'Лучше утром, меньше людей' },
    ]),
    tips: 'Кассы и тропа зависят от сезона — уточните перед выездом.',
    howToGet: 'Такси или автобус в сторону Мацесты / Змейковки, далее указатели к тропе.',
  },
  {
    id: 'place_psakho',
    slug: 'kanon-psakho',
    title: 'Каньон Псахо',
    summary: 'Бирюзовая река и «мокрый» или «сухой» каньон на выбор.',
    description:
      'Каньоны реки Псахо — один из сильных природных маршрутов Адлерского района: узкие стены, цвет воды и броды. Есть варианты с водой по колено и более сухой тропой. Не для шлёпанцев и не после ливня.',
    category: 'UNIQUE',
    address: 'г. Сочи, каньон Псахо (Адлерский район)',
    district: 'Адлер / горы',
    lat: 43.53,
    lng: 40.0,
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80',
    bestSeason: 'Июнь–сентябрь, не в грозу',
    visitTime: '3–5 часов',
    priceHint: 'Вход / сопровождение примерно от 400 ₽, гид дороже',
    sortOrder: 240,
    featuresJson: features([
      { icon: 'droplets', title: 'Броды', text: 'Мокрый каньон — в аквашузах' },
      { icon: 'boot', title: 'Средняя сложность', text: 'Не прогулка с коляской' },
      { icon: 'guide', title: 'С гидом спокойнее', text: 'Особенно в первый раз' },
    ]),
    tips: 'Следите за прогнозом: в паводок маршрут закрывают. Возьмите запасную одежду.',
    howToGet: 'Обычно трансфером из Адлера или с гидом; своим ходом — такси до начала тропы.',
  },
  {
    id: 'place_navalishchenskoe',
    slug: 'navalishchenskoe-ushchele',
    title: 'Навалищенское ущелье',
    summary: 'Узкое ущелье и смотровые над Хостой без дальнего выезда.',
    description:
      'Навалищенское (Навалишинское) ущелье — короткое, но эффектное: стены, река и смотровые площадки. Часто совмещают со Скайпарком: одно направление из города, разный характер прогулки.',
    category: 'MOUNTAIN',
    address: 'г. Сочи, Навалищенское ущелье',
    district: 'Хоста / Ахцу',
    lat: 43.53,
    lng: 39.87,
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80',
    bestSeason: 'Круглый год в сухую погоду',
    visitTime: '1–2 часа',
    priceHint: 'Вход примерно 200–350 ₽',
    sortOrder: 250,
    featuresJson: features([
      { icon: 'eye', title: 'Смотровые', text: 'Ущелье с безопасных площадок' },
      { icon: 'bridge', title: 'Рядом Скайпарк', text: 'Можно один выезд на два объекта' },
      { icon: 'camera', title: 'Камень и вода', text: 'Сильный кадр без длинного трека' },
    ]),
    tips: 'Перила мокрые после дождя. Не свешивайтесь за ограждение.',
    howToGet: 'Такси или автобус в сторону Скайпарка / Ахцу; часть гостей едет экскурсией.',
  },
  {
    id: 'place_health_path',
    slug: 'tropa-zdorovya',
    title: 'Приморская набережная / «тропа здоровья»',
    summary: 'Бесплатный променад вдоль моря от центра к Мамайке.',
    description:
      'Приморская набережная и участки «тропы здоровья» — ровный маршрут у воды: закаты, пробежки, самокаты. Без билетов и очередей. Хороший вечер после музеев центра или перед пляжем Ривьеры.',
    category: 'BEACH',
    address: 'г. Сочи, Приморская набережная',
    district: 'Центр / Мамайка',
    lat: 43.577,
    lng: 39.722,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
    bestSeason: 'Круглый год; летом после 18:00',
    visitTime: '1–3 часа',
    priceHint: 'Бесплатно',
    sortOrder: 260,
    featuresJson: features([
      { icon: 'footprints', title: 'Променад', text: 'Можно без машины' },
      { icon: 'sun', title: 'Закат', text: 'Классический вечерний маршрут' },
      { icon: 'bike', title: 'Спорт', text: 'Бег и самокаты, уступайте пешеходам' },
    ]),
    tips: 'Вечером людно. На роликах — звонок, много гуляющих с детьми.',
    howToGet: 'Пешком от Морского вокзала или Ривьеры; остановки транспорта вдоль Курортного проспекта.',
  },
  {
    id: 'place_riviera_park',
    slug: 'park-riviera',
    title: 'Парк «Ривьера»',
    summary: 'Городской парк с аттракционами у моря — не только пляж.',
    description:
      'Парк «Ривьера» — зелень, аттракционы, площадки и выход к пляжу. Отдельно от «просто полежать у моря»: здесь можно провести день с детьми, не уезжая в Адлер в Сочи-Парк.',
    category: 'PARK',
    address: 'г. Сочи, парк Ривьера',
    district: 'Центр',
    lat: 43.5895,
    lng: 39.716,
    image: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=1200&q=80',
    bestSeason: 'Апрель–октябрь',
    visitTime: '2–4 часа',
    priceHint: 'Вход в парк бесплатно; аттракционы примерно от 200 ₽',
    sortOrder: 270,
    featuresJson: features([
      { icon: 'ferris', title: 'Аттракционы', text: 'По жетонам / билетам' },
      { icon: 'trees', title: 'Тень', text: 'Аллеи между морем и городом' },
      { icon: 'users', title: 'Семья', text: 'Площадки и мороженое' },
    ]),
    tips: 'В выходные очереди на популярные горки. Совмещайте с пляжем Ривьера.',
    howToGet: 'Центр Сочи, остановки у парка Ривьера; пешком от Навагинской 20–25 минут.',
  },
  {
    id: 'place_hosta_beach',
    slug: 'plyazh-hosta',
    title: 'Пляж Хосты',
    summary: 'Галька и спокойнее, чем Ривьера в пик дня.',
    description:
      'Хостинский пляж — галька, вид на мыс и меньше «центральной» суеты. Удобно, если живёте в Хосте или едете к водопадам и хотите море в том же районе.',
    category: 'BEACH',
    address: 'г. Сочи, Хоста, пляж',
    district: 'Хоста',
    lat: 43.515,
    lng: 39.87,
    image: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=1200&q=80',
    bestSeason: 'Июнь–сентябрь',
    visitTime: '2–5 часов',
    priceHint: 'Пляж бесплатный; лежаки примерно от 300 ₽',
    sortOrder: 280,
    featuresJson: features([
      { icon: 'waves', title: 'Море', text: 'Галька — удобнее в аквашузах' },
      { icon: 'sun', title: 'Тише центра', text: 'Меньше транзитного потока' },
      { icon: 'map', title: 'Рядом тропы', text: 'Агура, роща, Ахун за день' },
    ]),
    tips: 'Проверяйте флаги спасателей. После шторма бывает водоросль.',
    howToGet: 'Электричка до Хосты или автобусы по Курортному проспекту, спуск к морю.',
  },
  {
    id: 'place_art_museum',
    slug: 'hudozhestvennyy-muzey',
    title: 'Сочинский художественный музей',
    summary: 'Живопись и графика в центре — план на жару или дождь.',
    description:
      'Художественный музей на Курортном проспекте: русское искусство и выставки. Короткий культурный слот между набережной и Зимним театром, без поездки в Адлер.',
    category: 'MUSEUM',
    address: 'г. Сочи, Курортный пр., 51',
    district: 'Центр',
    lat: 43.577,
    lng: 39.725,
    image: 'https://images.unsplash.com/photo-1566127444979-b3d2b64d626b?w=1200&q=80',
    bestSeason: 'Круглый год',
    visitTime: '45–90 минут',
    priceHint: 'Вход примерно 150–250 ₽',
    sortOrder: 290,
    featuresJson: features([
      { icon: 'book', title: 'Коллекция', text: 'Живопись и временные выставки' },
      { icon: 'cloud-rain', title: 'План Б', text: 'Кондиционер и тишина' },
      { icon: 'landmark', title: 'Рядом парадный Сочи', text: 'Театр, проспект, море' },
    ]),
    tips: 'Сверьте часы и санитарный день. Льготы — по документам на кассе.',
    howToGet: 'Курортный проспект, любой транспорт до остановки у театра / музея.',
  },
  {
    id: 'place_rosa_peak',
    slug: 'rosa-peak',
    title: 'Роза Пик',
    summary: 'Смотровая ~2320 м: Кавказ сверху, даже летом.',
    description:
      'Роза Пик — верхняя станция канаток Роза Хутор. Летом это панорама хребтов без лыж, зимой — старт трасс. На высоте холодно в любой месяц: ветровка обязательна.',
    category: 'VIEWPOINT',
    address: 'г. Сочи, Роза Хутор, Роза Пик',
    district: 'Красная Поляна',
    lat: 43.626,
    lng: 40.314,
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80',
    bestSeason: 'Ясные дни; зима — снег, лето — треккинг рядом',
    visitTime: '3–6 часов с дорогой и канаткой',
    priceHint: 'Подъём примерно от 2 000 ₽ в зависимости от сезона',
    sortOrder: 300,
    featuresJson: features([
      { icon: 'eye', title: 'Панорама', text: 'Одна из главных смотровых курорта' },
      { icon: 'mountain', title: 'Высота', text: 'Давление и ветер — не спешите' },
      { icon: 'coffee', title: 'Инфра наверху', text: 'Кафе, но цены выше, чем внизу' },
    ]),
    tips: 'Билеты онлайн. Не поднимайтесь при сильном ветре и закрытых очередях канатки.',
    howToGet: 'Сначала в Роза Хутор (Ласточка), затем очередь канаток по схеме курорта.',
  },
  {
    id: 'place_sochi_rail',
    slug: 'zheleznodorozhnyy-vokzal',
    title: 'Железнодорожный вокзал Сочи',
    summary: 'Сталинский ампир и пальмы — открытка у путей.',
    description:
      'Вокзал Сочи — не только транспорт: башня, колонны и пальмовый двор. 15–20 минут на фото, если приехали Ласточкой или ждёте поезд. Рядом выход к центру и Навагинской.',
    category: 'HISTORICAL',
    address: 'г. Сочи, ул. Горького, 56',
    district: 'Центр',
    lat: 43.5917,
    lng: 39.7283,
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=1200&q=80',
    bestSeason: 'Круглый год',
    visitTime: '20–40 минут',
    priceHint: 'Бесплатно (территория вокзала)',
    sortOrder: 310,
    featuresJson: features([
      { icon: 'landmark', title: 'Архитектура', text: 'Башня и дворик' },
      { icon: 'camera', title: 'Фото', text: 'Пальмы на фоне фасада' },
      { icon: 'map', title: 'Хаб', text: 'Отсюда удобно начинать день по центру' },
    ]),
    tips: 'Не мешайте пассажирам на перроне. Лучший свет — утро и золотой час.',
    howToGet: 'Любая электричка «Ласточка» или городской транспорт к вокзалу Сочи.',
  },
  {
    id: 'place_akhshtyr',
    slug: 'akhshtyrskaya-peschera',
    title: 'Ахштырская пещера',
    summary: 'Грот над Мзымтой — история и вид на ущелье.',
    description:
      'Ахштырская пещера — археологический объект и смотровая над долиной Мзымты. Короткий визит, но сильный контраст к пляжу Адлера. Часто включают в сборные туры вместе со Скайпарком.',
    category: 'UNIQUE',
    address: 'г. Сочи, Ахштырская пещера',
    district: 'Адлер / Ахцу',
    lat: 43.52,
    lng: 39.99,
    image: 'https://images.unsplash.com/photo-1504214208698-94b0d02d8e1c?w=1200&q=80',
    bestSeason: 'Круглый год',
    visitTime: '45–90 минут',
    priceHint: 'Вход примерно 200–400 ₽',
    sortOrder: 320,
    featuresJson: features([
      { icon: 'cave', title: 'Грот', text: 'Короткий подземный маршрут' },
      { icon: 'eye', title: 'Вид на Мзымту', text: 'Ущелье с площадки' },
      { icon: 'book', title: 'История', text: 'Стоянка древнего человека' },
    ]),
    tips: 'Внутри прохладно. Небольшой объект — не bulk весь день.',
    howToGet: 'Такси/экскурсия из Адлера по направлению к Красной Поляне, поворот к пещере.',
  },
  {
    id: 'place_berendeevo',
    slug: 'berendeevo-tsarstvo',
    title: 'Берендеево царство',
    summary: 'Водопады и сказочная тропа в Лазаревском районе.',
    description:
      'Комплекс «Берендеево царство» у Зубовой Щели: каскады, мостки и оформление «сказки». Семейная альтернатива 33 водопадам, если уже были в Кичмае или хотите короче по времени на тропе.',
    category: 'FAMILY',
    address: 'г. Сочи, Лазаревский р-н, Зубова Щель',
    district: 'Лазаревское',
    lat: 43.87,
    lng: 39.4,
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
    bestSeason: 'Май–октябрь',
    visitTime: '2–4 часа с дорогой',
    priceHint: 'Вход примерно 400–600 ₽',
    sortOrder: 330,
    featuresJson: features([
      { icon: 'droplets', title: 'Каскады', text: 'Мостки над водой' },
      { icon: 'users', title: 'С детьми', text: 'Короче, чем большой горный день' },
      { icon: 'camera', title: 'Декор тропы', text: '«Сказочный» маршрут' },
    ]),
    tips: 'Дорога из центра занимает время — закладывайте день. Обувь с протектором.',
    howToGet: 'Электричка до Лазаревской / Головинки плюс трансфер, либо экскурсионный автобус.',
  },
];

async function main() {
  console.log('Seeding places (Куда сходить в Сочи)…');
  for (const p of PLACES) {
    const data = {
      title: p.title,
      slug: p.slug,
      summary: p.summary,
      description: p.description,
      category: p.category,
      address: p.address,
      district: p.district,
      lat: p.lat,
      lng: p.lng,
      image: p.image,
      featuresJson: p.featuresJson,
      tips: packTips(p.howToGet, p.tips),
      bestSeason: p.bestSeason,
      visitTime: p.visitTime,
      priceHint: p.priceHint,
      status: 'PUBLISHED',
      sortOrder: p.sortOrder,
      isDemoData: true,
    };
    await prisma.place.upsert({
      where: { id: p.id },
      create: { id: p.id, ...data },
      update: data,
    });
    console.log('  ✓', p.title);
  }
  console.log(`Done: ${PLACES.length} places`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
